export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const VERIFY_EMAIL_USER = "VERIFY_EMAIL_USER";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_ALL_EXERCISE_TYPE = "GET_ALL_EXERCISE_TYPE";
export const GET_ONE_EXERCISE_TYPE = "GET_ONE_EXERCISE_TYPE";
export const UPDATE_ONE_EXERCISE_TYPE = "UPDATE_ONE_EXERCISE_TYPE";
export const CREATE_ONE_TRAINING = "CREATE_ONE_TRAINING";

export const ADD_ONE_WORKOUT = "ADD_ONE_WORKOUT";
export const ADD_ARRAY_OF_WORKOUTS = "ADD_ARRAY_OF_WORKOUTS";
export const GET_ALL_WORKOUTS = "GET_ALL_WORKOUTS";
export const SWAP_WORKOUT_UP = "SWAP_WORKOUT_UP";
export const SWAP_WORKOUT_DOWN = "SWAP_WORKOUT_DOWN";
export const DELETE_WORKOUT = "DELETE_WORKOUT";

export const DELETE_ONE_TYPE_EXERCISE = "DELETE_ONE_TYPE_EXERCISE";

export const GET_ONE_WORKOUT = "GET_ONE_WORKOUT";
export const UPDATE_ONE_WORKOUT = "UPDATE_ONE_WORKOUT";

export const GET_ALL_TRAINIGS = "GET_ALL_TRAINIGS";
export const GET_ONE_TRAINIG = "GET_ONE_TRAINIG";
export const ADD_ONE_TRAINIG = "ADD_ONE_TRAINIG";
export const UPDATE_ONE_TRAINIG = "UPDATE_ONE_TRAINIG";
export const DELETE_ONE_TRAINIG = "DELETE_ONE_TRAINIG";

export const GET_WORKS_IN_TRAINING = "GET_WORKS_IN_TRAINING";
export const CLEAR_ALL_WORKS = "CLEAR_ALL_WORKS";

export const SET_VISIBLE_PAGE = "SET_VISIBLE_PAGE";
